[package]
name = "xiangshan-worker"
version = "0.1.0"
edition = "2021"
authors = ["Han Xiao <ringsaturn.me@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.8", features = ['http'] }
worker-macros = { version = "0.8", features = ['http'] }
http = "1.3"
geometry-rs = "0.4.1"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"

[profile.release]
lto = true
strip = true
codegen-units = 1
